name: WildPE
main: WildPE\wild
api: [2.1.0, 3.0.0]
author: SinlesFlyer376
description: WildPE
commands:
     wild:
       description: "teleport to a random position in the world"
       permission: factionscore.command.wild
permissions:
     factioncore.command.wild:
         default: op
